#!/bin/bash
#!/bin/bash

# List of GitHub URLs for the files you need to download
file_urls=(
    "https://raw.githubusercontent.com/Wondahs/RSA-Factoring-Challenge/main/c_function.c"

    "https://raw.githubusercontent.com/Wondahs/RSA-Factoring-Challenge/main/python/factors.py"
)

# Loop through the URLs and use curl to download each file
for url in "${file_urls[@]}"; do
    curl -O -L -s "$url"
done

chmod +x factors.py
gcc -shared c_function.c -o my_library.so

export LD_LIBRARY_PATH="."
./factors.py $1
